Repository DevCrew-io/camerakit-flutter, pull requests merged in 2023-10, with the labels that each got.

#10 Add Documentation
  README.md
  android/src/main/kotlin/com/camerakit/camerakit_flutter/CamerakitFlutterPlugin.kt
  android/src/main/kotlin/com/camerakit/camerakit_flutter/Configuration.kt
  android/src/main/kotlin/com/camerakit/camerakit_flutter/Constants.kt
  android/src/main/kotlin/com/camerakit/camerakit_flutter/StringExtentions.kt
  example/lib/constants.dart
  lib/camerakit_flutter.dart
  lib/camerakit_flutter_method_channel.dart
  lib/camerakit_flutter_platform_interface.dart
  lib/configuration_camerakit.dart
  lib/lens_model.dart
  screenshots/1a.png
  screenshots/2b.png
  screenshots/3c.png
  screenshots/camerakit_video.mp4
Labels: documentation

#13 Update README.md
  README.md
Labels: documentation

#14 Update README.md
  README.md
Labels: documentation

#15 Update README.md
  README.md
Labels: documentation

#16 Refactor code and documentation
  CHANGELOG.md
  example/lib/media_result_screen.dart
  pubspec.yaml
  test/camerakit_flutter_test.dart
Labels: documentation

#17 chore: bump version to 0.0.3
  CHANGELOG.md
  pubspec.yaml
Labels: documentation

#18 refactor: improve pub points
  CHANGELOG.md
  example/lib/constants.dart
  example/lib/lens_list_screen.dart
  example/lib/media_result_screen.dart
  lib/camerakit_flutter.dart
  lib/camerakit_flutter_method_channel.dart
  lib/configuration_camerakit.dart
  pubspec.yaml
  test/camerakit_flutter_test.dart
Labels: refactor

#19 Add pub badge in readme
  README.md
Labels: documentation

#21 Security fix
  android/src/main/AndroidManifest.xml
  android/src/main/kotlin/com/camerakit/camerakit_flutter/Configuration.kt
  example/lib/main.dart
  lib/camerakit_flutter_method_channel.dart
  lib/configuration_camerakit.dart
Labels: Security fix

#23 Upgrade Camerakit version
  CHANGELOG.md
  README.md
  android/build.gradle
  android/src/main/AndroidManifest.xml
  example/ios/Podfile.lock
  example/lib/constants.dart
  example/lib/main.dart
  example/pubspec.lock
  ios/Classes/CamerakitFlutterPlugin.swift
  ios/Classes/Configuration.swift
  ios/camerakit_flutter.podspec
  lib/configuration_camerakit.dart
  pubspec.yaml
Labels: refactor
